In [24]:
import pandas as pd
from pathlib import Path
import sys

# Path.cwd() returns the 'notebooks' directory, so .parent gets you 'sante-occitanie'
project_root = str(Path.cwd().parent)

# Append the project root if it is not already in sys.path
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from scripts.config import OCCITANIE_DEPTS

In [25]:
RAW_DATA_DIR = Path('__file__').resolve().parent.parent / "data" / "raw"
raw_hospital = RAW_DATA_DIR / "hospital_covid_raw.csv"

In [26]:
hospital_df = pd.read_csv(raw_hospital, sep=';')
hospital_df.head()

  dep  sexe        jour  hosp  rea  HospConv  SSR_USLD  autres  rad  dc
0  01     0  2020-03-18     2    0       NaN       NaN     NaN    1   0
1  01     1  2020-03-18     1    0       NaN       NaN     NaN    1   0
2  01     2  2020-03-18     1    0       NaN       NaN     NaN    0   0
3  02     0  2020-03-18    41   10       NaN       NaN     NaN   18  11
4  02     1  2020-03-18    19    4       NaN       NaN     NaN   11   6

In [13]:
df = hospital_df[hospital_df['sexe'] == 0]
df

,dep,sexe,jour,hosp,rea,HospConv,SSR_USLD,autres,rad,dc
0,01,0,2020-03-18,2,0,NaN,NaN,NaN,1,0
3,02,0,2020-03-18,41,10,NaN,NaN,NaN,18,11
6,03,0,2020-03-18,4,0,NaN,NaN,NaN,1,0
9,04,0,2020-03-18,3,1,NaN,NaN,NaN,2,0
12,05,0,2020-03-18,8,1,NaN,NaN,NaN,9,0
...,...,...,...,...,...,...,...,...,...,...
338231,972,0,2023-03-31,14,0,12.0,2.0,0.0,4669,1101
338234,973,0,2023-03-31,4,1,3.0,0.0,0.0,6330,410
338237,974,0,2023-03-31,27,5,14.0,8.0,0.0,8876,980
338240,976,0,2023-03-31,0,0,0.0,0.0,0.0,1766,163
338243,978,0,2023-03-31,0,0,0.0,0.0,0.0,0,0

In [29]:
df = df[df['dep'].astype(str).str.zfill(2).isin(OCCITANIE_DEPTS)].copy()
df

       dep  sexe        jour  hosp  rea  HospConv  SSR_USLD  autres   rad   dc
24      09     0  2020-03-18     1    1       NaN       NaN     NaN     2    0
30      11     0  2020-03-18     8    7       NaN       NaN     NaN     9    3
33      12     0  2020-03-18     7    2       NaN       NaN     NaN     1    0
90      30     0  2020-03-18     5    3       NaN       NaN     NaN     6    0
93      31     0  2020-03-18    23    5       NaN       NaN     NaN    11    0
...     ..   ...         ...   ...  ...       ...       ...     ...   ...  ...
338084  48     0  2023-03-31     2    0       2.0       0.0     0.0   785  164
338135  65     0  2023-03-31    30    2      27.0       1.0     0.0  3980  489
338138  66     0  2023-03-31    89    1      20.0      59.0     9.0  5231  910
338183  81     0  2023-03-31    35    3      20.0      11.0     1.0  3699  658
338186  82     0  2023-03-31    21    5       9.0       7.0     0.0  2640  424

[14417 rows x 10 columns]

In [32]:
df["jour"] = pd.to_datetime(df["jour"])

In [33]:
df = df.rename(columns={
        "dep":  "dept_id",
        "jour": "date",
        "hosp": "hosp_occupied",
        "rea":  "icu_occupied",
        "rad":  "returned_home_cumul",
        "dc":   "deaths_cumul",
    })

df

,dept_id,sexe,date,hosp_occupied,icu_occupied,HospConv,SSR_USLD,autres,returned_home_cumul,deaths_cumul
24,09,0,2020-03-18,1,1,NaN,NaN,NaN,2,0
30,11,0,2020-03-18,8,7,NaN,NaN,NaN,9,3
33,12,0,2020-03-18,7,2,NaN,NaN,NaN,1,0
90,30,0,2020-03-18,5,3,NaN,NaN,NaN,6,0
93,31,0,2020-03-18,23,5,NaN,NaN,NaN,11,0
...,...,...,...,...,...,...,...,...,...,...
338084,48,0,2023-03-31,2,0,2.0,0.0,0.0,785,164
338135,65,0,2023-03-31,30,2,27.0,1.0,0.0,3980,489
338138,66,0,2023-03-31,89,1,20.0,59.0,9.0,5231,910
338183,81,0,2023-03-31,35,3,20.0,11.0,1.0,3699,658
338186,82,0,2023-03-31,21,5,9.0,7.0,0.0,2640,424